version: '3'

services:
    express:
        build:
            context: ./
        ports:
            - '3001:3001'
        environment:
            - PORT=3001
            - NODE_ENV=development
        volumes:
            - './app:/app'