version: "3"

services:
  nodebb:
    image: vimagick/nodebb
    ports:
      - "4567:4567"
    links:
      - redis
    volumes:
      - ./data:/var/lib/nodebb
      - /usr/src/nodebb/build
      - /usr/src/nodebb/node_modules
      - /usr/src/nodebb/public/uploads
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./data:/data
    restart: always